import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ApiService {

  items: any[] = [
    {
      id: '1',
      name: 'C2 Solo Apple',
      price: 14.00,
      status: true,
      rating: 4.9,
      cover: 'assets/juices/1_C2APPLE.png',
      description: 'Refreshing green tea with a crisp apple flavor in a handy 230ml bottle, perfect for on-the-go enjoyment.',
    },
    {
      id: '2',
      name: 'Oishi Smart C+ Pomelo',
      price: 60.25,
      status: true,
      rating: 4.9,
      cover: 'assets/juices/2_SMARTCPOMELO.png',
      description: 'Oishi Smart C+ Pomelo Grapefruit Juice Drink 1L is a refreshing beverage packed with Vitamin C, offering a tangy and sweet pomelo grapefruit flavor to keep you energized and hydrated.',
    },
    {
      id: '3',
      name: 'Motts 100%  Apple',
      price: 357.75,
      status: true,
      rating: 4.9,
      cover: 'assets/juices/3_MOTTSAPPLE.png',
      description: 'Motts 100% Apple Juice Original 64oz delivers a pure and refreshing apple flavor made from real apples, with no added sugar. Perfect for a natural and nutritious beverage choice.',
    },
    {
      id: '4',
      name: 'Mogu Mogu Coconut',
      price: 46.25,
      status: true,
      rating: 4.9,
      cover: 'assets/juices/4_MOGUCOCONUT.png',
      description: 'Mogu Mogu Coconut Juice with Nata de Coco 320ml is a refreshing tropical drink combining natural coconut juice with chewy nata de coco bits for a delightful and fun sipping experience.',
    },
    {
      id: '5',
      name: 'Del Monte Mango Juice',
      price: 110.50,
      status: true,
      rating: 4.9,
      cover: 'assets/juices/5_DELMANGO.png',
      description: 'Del Monte Mango Juice Drink 1L offers a rich and refreshing taste of real mangoes, perfect for quenching your thirst and enjoying a burst of tropical flavor.',
    },
    {
      id: '6',
      name: 'Langers Apple Juice',
      price: 144.25,
      status: true,
      rating: 4.9,
      cover: 'assets/juices/6_ANGERSAPPLE.png',
      description: 'Langers Apple Juice Cocktail 32oz delivers a crisp and refreshing blend of apple flavors, providing a sweet and tangy drink thats perfect for any occasion.',
    },
    {
      id: '7',
      name: 'C2 Classic Green Tea',
      price: 32.00,
      status: true,
      rating: 4.9,
      cover: 'assets/juices/7_C2GREEN.png',
      description: 'C2 Classic Green Tea 500ml offers a refreshing, light, and smooth green tea experience with a hint of natural sweetness, making it the perfect drink to quench your thirst throughout the day.',
    },
    {
      id: '8',
      name: 'Welchs 100% Grape Juice',
      price: 428.00,
      status: true,
      rating: 4.9,
      cover: 'assets/juices/8_WELCHGRAPE.png',
      description: 'Welchs 100% Grape Juice 46oz is a rich and naturally sweet juice made from premium Concord grapes, offering a pure, full-bodied flavor packed with antioxidants and nutrients. Perfect for a refreshing and healthy drink.',
    },
    {
      id: '9',
      name: 'Fit n Right Green Apple',
      price: 33.75,
      status: true,
      rating: 4.9,
      cover: 'assets/juices/9_FITAPPLE.png',
      description: 'Del Monte Fit n Right Green Apple Juice Drink 330ml is a refreshing, low-calorie beverage made with the natural goodness of green apples, offering a crisp and invigorating taste. Perfect for a light, healthy refreshment.',
    },
    {
      id: '10',
      name: 'C2 Lemon Flavored',
      price: 27.25,
      status: true,
      rating: 4.9,
      cover: 'assets/juices/10_C2LEMON.png',
      description: 'C2 Lemon Flavored Green Tea 355ml is a crisp and refreshing drink that combines the smooth taste of green tea with a zesty lemon flavor, offering a perfect balance of refreshment and health benefits in every sip.',
    },
    {
      id: '11',
      name: 'Del Monte Pineapple',
      price: 104.75,
      status: true,
      rating: 4.9,
      cover: 'assets/juices/11_DELPINE.png',
      description: 'Del Monte Pineapple Blueberry Juice Drink 1L blends the tropical sweetness of pineapple with the tangy flavor of blueberries, creating a deliciously refreshing and fruity drink perfect for any occasion.',
    },
    {
      id: '12',
      name: 'Minute Maid Orange',
      price: 64.75,
      status: true,
      rating: 4.9,
      cover: 'assets/juices/12_MINORANGE.png',
      description: 'Minute Maid Nutri+ Orange Juice Drink 1L is a nutritious and refreshing beverage made with real orange juice, enriched with vitamins and minerals to support a healthy lifestyle while offering a delicious citrusy flavor.',
    },
    {
      id: '13',
      name: 'Old Orchard Cranberry',
      price: 335.75,
      status: true,
      rating: 4.9,
      cover: 'assets/juices/13_ORCHARDAPPLE.png',
      description: 'Old Orchard Apple Cranberry Juice Drink 64oz blends the tartness of cranberries with the sweetness of apples, offering a refreshing and healthy beverage rich in antioxidants and vitamin C. Perfect for any occasion, it provides a delicious and tangy twist on traditional juice drinks.',
    },
    {
      id: '14',
      name: 'Mogu Mogu Grape',
      price: 46.25,
      status: true,
      rating: 4.9,
      cover: 'assets/juices/14_MOGUGRAPE.png',
      description: 'Mogu Mogu Grape Juice with Nata de Coco 320ml combines the sweetness of grape juice with chewy nata de coco bits, offering a fun and refreshing drink experience. Packed with flavor and texture, its a delightful, tropical beverage perfect for those who enjoy a little extra bite in their drinks.',
    },
    {
      id: '15',
      name: 'Minute Maid Orange',
      price: 18.25,
      status: true,
      rating: 4.9,
      cover: 'assets/juices/15_MINUTEORANGE.png',
      description: 'Minute Maid Fresh Orange Juice Drink 250ml is a refreshing and natural-tasting juice made from the finest oranges. With its tangy and sweet flavor, it offers a quick burst of freshness, making it a perfect choice for a healthy, on-the-go beverage.',
    },
    {
      id: '16',
      name: 'C2 Peach Flavored',
      price: 32.00,
      status: true,
      rating: 4.9,
      cover: 'assets/juices/16_C2PEACH.png',
      description: 'C2 Peach Flavored Black Tea 500ml offers a deliciously refreshing blend of black tea and sweet peach flavor. With its smooth and invigorating taste, it provides a perfect balance of fruity sweetness and tea, ideal for a revitalizing drink any time of the day.',
    },
    {
      id: '17',
      name: 'Oishi Smart C+ Orange',
      price: 60.25,
      status: true,
      rating: 4.9,
      cover: 'assets/juices/17_SMARTLEMON.png',
      description: 'Oishi Smart C+ Orange Crush Juice Drink 1L is a tangy and refreshing orange juice with added Vitamin C. Packed with a bold citrus flavor, this drink offers a burst of energy and hydration, perfect for quenching your thirst while supporting your immune system.',
    },
    {
      id: '18',
      name: 'Fit n Right Four Seasons',
      price: 33.75,
      status: true,
      rating: 4.9,
      cover: 'assets/juices/18_FITMANGO.png',
      description: 'Del Monte Fit n Right Original Four Seasons Juice Drink 330ml is a refreshing blend of tropical fruits, offering a delicious combination of flavors. Perfect for a healthy and invigorating drink, it’s low in calories and a great way to enjoy a refreshing boost throughout the day.',
    },
    {
      id: '19',
      name: 'Fitn  Right Burn Apple',
      price: 86.50,
      status: true,
      rating: 4.9,
      cover: 'assets/juices/19_FITBURN.png',
      description: 'Del Monte Fit n Right Burn Apple Juice Drink 1L is a refreshing and invigorating apple juice drink, specially crafted with a blend of apple flavor and natural ingredients to help support your weight management journey. It’s a healthy, low-calorie drink option that aids metabolism while providing a crisp, satisfying taste.',
    },
    {
      id: '20',
      name: 'Fruity Zing Calamansi',
      price: 28.25,
      status: true,
      rating: 4.9,
      cover: 'assets/juices/20_FRUITYMANSI.png',
      description: 'Del Monte Fruity Zing Calamansi Lemon Flavor Juice Drink 330ml is a zesty and refreshing beverage, packed with the tangy taste of calamansi and lemon. This thirst-quenching drink offers a burst of citrus flavor and a revitalizing experience, perfect for a quick refreshment anytime.',
    },
  ];

  constructor() { }
}

